/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pluto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Agregarjuego extends javax.swing.JFrame {
    
    DefaultTableModel modelo2 = new DefaultTableModel();
    /**
     * Creates new form Agregarjuego
     */
    public Agregarjuego() {
        initComponents();
        Creartabla();
        CreartablaI();
    }
    public void Creartabla(){
       
 
        try
        {
            DefaultTableModel modelo = new DefaultTableModel();
            tablanombrejuegos.setModel(modelo);
        
            PreparedStatement ps = null;
            ResultSet rs = null;
            ConexionMySQL conn = new ConexionMySQL();
            Connection con = conn.ConectarBasedeDatos(); 
            
            String sql = "SELECT id_juego, nombre FROM Juego ";
            System.out.println(sql);
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            
            java.sql.ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas=rsMd.getColumnCount();
            

             modelo.addColumn("ID");
            modelo.addColumn("Nombre");

            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i=0; i<cantidadColumnas; i++){
                    filas[i] = rs.getObject( i + 1 );    
                }
                modelo.addRow(filas);
            }

            
          
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString(), "Error ", JOptionPane.ERROR_MESSAGE);
        }
    }
    
       
    public void CreartablaI(){
        try
        {
            tinversion.setModel(modelo2);
        
            PreparedStatement ps = null;
            ResultSet rs = null;
            ConexionMySQL conn = new ConexionMySQL();
            Connection con = conn.ConectarBasedeDatos(); 
            
            String sql = "SELECT id_usuario, id_juego, monto FROM Inversion ";
            System.out.println(sql);
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            
            java.sql.ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas=rsMd.getColumnCount();
            
            modelo2.addColumn("Operaciones");
            modelo2.addColumn("Juego");
            modelo2.addColumn("Monto");

            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i=0; i<cantidadColumnas; i++){
                    filas[i] = rs.getObject( i + 1 );    
                }
                modelo2.addRow(filas);
            }

            
          
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString(), "Error ", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }

    public JPanel getFondo() {
          return bg;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtagregarjuego = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablanombrejuegos = new javax.swing.JTable();
        thinkingbtm = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tinversion = new javax.swing.JTable();
        Txtid = new javax.swing.JTextField();
        Txtmonto = new javax.swing.JTextField();
        nombrelb = new javax.swing.JLabel();
        nombrelb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtagregarjuego.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        txtagregarjuego.setForeground(new java.awt.Color(204, 204, 204));
        txtagregarjuego.setText("Agregá tus inversiones");
        bg.add(txtagregarjuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        tablanombrejuegos.setBackground(new java.awt.Color(37, 36, 36));
        tablanombrejuegos.setForeground(new java.awt.Color(204, 204, 204));
        tablanombrejuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablanombrejuegos);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, 430));

        thinkingbtm.setBackground(new java.awt.Color(247, 147, 50));
        thinkingbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thinkingbtm.setForeground(new java.awt.Color(0, 0, 0));
        thinkingbtm.setText("Agregar Inversion");
        thinkingbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thinkingbtmActionPerformed(evt);
            }
        });
        bg.add(thinkingbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, -1));

        tinversion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Juego", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tinversion);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 330, 250));
        bg.add(Txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 160, -1));
        bg.add(Txtmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 160, -1));

        nombrelb.setForeground(new java.awt.Color(204, 204, 204));
        nombrelb.setText("ID:");
        bg.add(nombrelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        nombrelb1.setForeground(new java.awt.Color(204, 204, 204));
        nombrelb1.setText("Tu inversion:");
        bg.add(nombrelb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thinkingbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thinkingbtmActionPerformed
        PreparedStatement ps=null;
        try{
        ConexionMySQL conn = new ConexionMySQL();
        Connection con = conn.ConectarBasedeDatos(); 
            
        String sql = "INSERT INTO Inversion (id_usuario, id_juego, monto) VALUES (?,?,?)";
        ps = con.prepareStatement(sql);
        ps.setInt(1, 1);
        ps.setString(2, Txtid.getText());
        ps.setString(3, Txtmonto.getText()); 
        ps.execute();
        
        JOptionPane.showMessageDialog(null, "Inversión Guardada!!");
        Object[] fila = new Object[3];
        fila[0]=1;
        fila[1]=Txtid.getText();
        fila[2]=Txtmonto.getText();
        modelo2.addRow(fila);
        
            

   
            
        
        
        }catch(SQLException ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_thinkingbtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregarjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregarjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregarjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregarjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregarjuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Txtid;
    public javax.swing.JTextField Txtmonto;
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombrelb;
    private javax.swing.JLabel nombrelb1;
    private javax.swing.JTable tablanombrejuegos;
    private javax.swing.JButton thinkingbtm;
    private javax.swing.JTable tinversion;
    private javax.swing.JLabel txtagregarjuego;
    // End of variables declaration//GEN-END:variables
}
