/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pluto;


import com.mysql.cj.jdbc.result.ResultSetMetaData;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class Juegosjf extends javax.swing.JFrame {

    /**
     * Creates new form Juegosjf
     */
    public Juegosjf() {
        initComponents();
        Creartabla();
            
          
       
    }
    
    public void Creartabla(){
        
        String campo1=Txtnombre.getText();
        String campo2=Txtblock.getText();
        String campo3=Txtcategoria.getText();
        String where = "";
        
        if(!"".equals(campo1)){
            where = "WHERE nombre ='"+campo1+"'";
        }
        if(!"".equals(campo2)){
            where = "WHERE blockchain ='"+campo2+"'";
        }
        if(!"".equals(campo3)){
            where = "WHERE categoria ='"+campo3+"'";
        }        
        try
        {
            DefaultTableModel modelo = new DefaultTableModel();
            tablajuegos.setModel(modelo);
        
            PreparedStatement ps = null;
            ResultSet rs = null;
            ConexionMySQL conn = new ConexionMySQL();
            Connection con = conn.ConectarBasedeDatos(); 
            
            String sql = "SELECT nombre, blockchain, token, categoria, descripcion, imagen FROM Juego " + where;
            System.out.println(sql);
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            
            java.sql.ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas=rsMd.getColumnCount();
            

            modelo.addColumn("Nombre");
            modelo.addColumn("Blockchain");
            modelo.addColumn("Token");
            modelo.addColumn("Categoria");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Imagen");
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i=0; i<cantidadColumnas; i++){
                    filas[i] = rs.getObject( i + 1 );    
                }
                modelo.addRow(filas);
            }
            Txtnombre.setText("");
            Txtblock.setText("");
            Txtcategoria.setText("");
            
          
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString(), "Error ", JOptionPane.ERROR_MESSAGE);
        }
    
    
        
    }
    
    public JPanel getFondo() {
        return bg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablajuegos = new javax.swing.JTable();
        ldjlbl = new javax.swing.JLabel();
        categorialb = new javax.swing.JLabel();
        Txtnombre = new javax.swing.JTextField();
        Txtblock = new javax.swing.JTextField();
        Txtcategoria = new javax.swing.JTextField();
        categoriabtm = new javax.swing.JButton();
        borrarfiltrobtm = new javax.swing.JButton();
        blockbtm = new javax.swing.JButton();
        buscarporlb1 = new javax.swing.JLabel();
        nombrelb = new javax.swing.JLabel();
        blocklb = new javax.swing.JLabel();
        nombrebtm1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablajuegos.setBackground(new java.awt.Color(37, 36, 36));
        tablajuegos.setForeground(new java.awt.Color(204, 204, 204));
        tablajuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Blockchain", "Categoria", "Descripcion", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablajuegos);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 1000, 330));

        ldjlbl.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        ldjlbl.setForeground(new java.awt.Color(204, 204, 204));
        ldjlbl.setText("LISTA DE JUEGOS");
        bg.add(ldjlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        categorialb.setForeground(new java.awt.Color(204, 204, 204));
        categorialb.setText("Categoria:");
        bg.add(categorialb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));
        bg.add(Txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 190, -1));
        bg.add(Txtblock, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 190, -1));
        bg.add(Txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 190, -1));

        categoriabtm.setBackground(new java.awt.Color(247, 147, 50));
        categoriabtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        categoriabtm.setForeground(new java.awt.Color(0, 0, 0));
        categoriabtm.setText("Buscar");
        categoriabtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriabtmActionPerformed(evt);
            }
        });
        bg.add(categoriabtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 80, -1));

        borrarfiltrobtm.setBackground(new java.awt.Color(247, 147, 50));
        borrarfiltrobtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        borrarfiltrobtm.setForeground(new java.awt.Color(0, 0, 0));
        borrarfiltrobtm.setText("Borrar Filtro");
        borrarfiltrobtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarfiltrobtmActionPerformed(evt);
            }
        });
        bg.add(borrarfiltrobtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, -1));

        blockbtm.setBackground(new java.awt.Color(247, 147, 50));
        blockbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        blockbtm.setForeground(new java.awt.Color(0, 0, 0));
        blockbtm.setText("Buscar");
        blockbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockbtmActionPerformed(evt);
            }
        });
        bg.add(blockbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 80, -1));

        buscarporlb1.setForeground(new java.awt.Color(204, 204, 204));
        buscarporlb1.setText("Buscar por:");
        bg.add(buscarporlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        nombrelb.setForeground(new java.awt.Color(204, 204, 204));
        nombrelb.setText("Nombre:");
        bg.add(nombrelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        blocklb.setForeground(new java.awt.Color(204, 204, 204));
        blocklb.setText("Blockchain:");
        bg.add(blocklb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        nombrebtm1.setBackground(new java.awt.Color(247, 147, 50));
        nombrebtm1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombrebtm1.setForeground(new java.awt.Color(0, 0, 0));
        nombrebtm1.setText("Buscar");
        nombrebtm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrebtm1ActionPerformed(evt);
            }
        });
        bg.add(nombrebtm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarfiltrobtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarfiltrobtmActionPerformed
        Creartabla();
    }//GEN-LAST:event_borrarfiltrobtmActionPerformed

    private void nombrebtm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrebtm1ActionPerformed
        Creartabla();
    }//GEN-LAST:event_nombrebtm1ActionPerformed

    private void blockbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockbtmActionPerformed
        Creartabla();
    }//GEN-LAST:event_blockbtmActionPerformed

    private void categoriabtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriabtmActionPerformed
        Creartabla();
    }//GEN-LAST:event_categoriabtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juegosjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juegosjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juegosjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juegosjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juegosjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Txtblock;
    public javax.swing.JTextField Txtcategoria;
    public javax.swing.JTextField Txtnombre;
    private javax.swing.JPanel bg;
    private javax.swing.JButton blockbtm;
    private javax.swing.JLabel blocklb;
    private javax.swing.JButton borrarfiltrobtm;
    private javax.swing.JLabel buscarporlb1;
    private javax.swing.JButton categoriabtm;
    private javax.swing.JLabel categorialb;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ldjlbl;
    private javax.swing.JButton nombrebtm1;
    private javax.swing.JLabel nombrelb;
    private javax.swing.JTable tablajuegos;
    // End of variables declaration//GEN-END:variables
}
