/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pluto;

import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        userlabel = new javax.swing.JLabel();
        Txtusuario = new javax.swing.JTextField();
        passlabel = new javax.swing.JLabel();
        Txtpass = new javax.swing.JPasswordField();
        login = new javax.swing.JLabel();
        loginbtm = new javax.swing.JButton();
        taskbarbg = new javax.swing.JPanel();
        plutotxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtregister = new javax.swing.JLabel();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");

        bg.setBackground(new java.awt.Color(37, 36, 36));
        bg.setForeground(new java.awt.Color(166, 164, 164));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userlabel.setForeground(new java.awt.Color(212, 212, 212));
        userlabel.setText("Usuario");
        bg.add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 206, -1, -1));
        bg.add(Txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 228, 250, -1));

        passlabel.setForeground(new java.awt.Color(212, 212, 212));
        passlabel.setText("contraseña");
        bg.add(passlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 275, -1, -1));

        Txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtpassActionPerformed(evt);
            }
        });
        bg.add(Txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 297, 250, -1));

        login.setBackground(new java.awt.Color(212, 212, 212));
        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(212, 212, 212));
        login.setText("Log In");
        login.setToolTipText("");
        bg.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        loginbtm.setBackground(new java.awt.Color(247, 147, 50));
        loginbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginbtm.setForeground(new java.awt.Color(0, 0, 0));
        loginbtm.setText("LOGIN");
        loginbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtmActionPerformed(evt);
            }
        });
        bg.add(loginbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 116, -1));

        taskbarbg.setBackground(new java.awt.Color(0, 0, 0));
        taskbarbg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        plutotxt.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        plutotxt.setForeground(new java.awt.Color(247, 147, 50));
        plutotxt.setText("PLUTO");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pluto/images/logochichitofinal.png"))); // NOI18N

        javax.swing.GroupLayout taskbarbgLayout = new javax.swing.GroupLayout(taskbarbg);
        taskbarbg.setLayout(taskbarbgLayout);
        taskbarbgLayout.setHorizontalGroup(
            taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plutotxt)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        taskbarbgLayout.setVerticalGroup(
            taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarbgLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(taskbarbgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(plutotxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(taskbarbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 911, 70));

        txtregister.setForeground(new java.awt.Color(212, 212, 212));
        txtregister.setText("¿No tienes una cuenta?");
        bg.add(txtregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        register.setBackground(new java.awt.Color(37, 36, 36));
        register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("EMPIEZA YA");
        register.setBorder(null);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        bg.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtmActionPerformed
        try{
            ConexionMySQL Con = new ConexionMySQL();
            String u = Txtusuario.getText();
            String p = Txtpass.getText();
            Con.ConectarBasedeDatos();
            
            String SQL = "SELECT id_usuario, usuario FROM Usuario WHERE usuario='"+u+"' AND contra='"+p+"'";
            Con.resultado = Con.sentencia.executeQuery(SQL);
            if(Con.resultado.next()){
                setVisible(false);
                Menu menu = new Menu();
                Panelmenu menup = new Panelmenu();
                menu.setVisible(true);
                //menup.LbUsuario.setText(""+Con.resultado.getString("usuario"));
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o contraseña no van pa");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex. getMessage()); 
        }
        
        
    }//GEN-LAST:event_loginbtmActionPerformed

    private void TxtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtpassActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        setVisible(false);
        Register register = new Register();
        register.setVisible(true);
        
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPasswordField Txtpass;
    public javax.swing.JTextField Txtusuario;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel login;
    private javax.swing.JButton loginbtm;
    private javax.swing.JLabel passlabel;
    private javax.swing.JLabel plutotxt;
    private javax.swing.JButton register;
    private javax.swing.JPanel taskbarbg;
    private javax.swing.JLabel txtregister;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
