/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pluto;


import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Panelmenu menu1 = new Panelmenu();
        Cambiarcontent(menu1.getFondo());
        
        this.setLocationRelativeTo(null);
        
    }
    
    private void Cambiarcontent (JPanel p){
        p.setSize(1276, 645);
        p.setLocation(0, 0);
        content.removeAll();
        content.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        content.revalidate();
        content.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        taskbarbg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        vsngralbtm = new javax.swing.JButton();
        Juegosbtm = new javax.swing.JButton();
        logoutgtm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        plutobtm = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pluto");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        content.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(37, 36, 36));
        jSeparator2.setForeground(new java.awt.Color(37, 36, 36));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(640, Short.MAX_VALUE))
        );

        taskbarbg.setBackground(new java.awt.Color(0, 0, 0));
        taskbarbg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pluto/images/logochichitofinal.png"))); // NOI18N

        vsngralbtm.setBackground(new java.awt.Color(37, 36, 36));
        vsngralbtm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vsngralbtm.setForeground(new java.awt.Color(204, 204, 204));
        vsngralbtm.setText("Vision General");
        vsngralbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsngralbtmActionPerformed(evt);
            }
        });

        Juegosbtm.setBackground(new java.awt.Color(0, 0, 0));
        Juegosbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Juegosbtm.setForeground(new java.awt.Color(204, 204, 204));
        Juegosbtm.setText("Juegos");
        Juegosbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuegosbtmActionPerformed(evt);
            }
        });

        logoutgtm.setBackground(new java.awt.Color(247, 147, 50));
        logoutgtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutgtm.setForeground(new java.awt.Color(0, 0, 0));
        logoutgtm.setText("Cerrar Sesión");
        logoutgtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutgtmActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(37, 36, 36));
        jSeparator1.setForeground(new java.awt.Color(37, 36, 36));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        plutobtm.setBackground(new java.awt.Color(0, 0, 0));
        plutobtm.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        plutobtm.setForeground(new java.awt.Color(247, 147, 50));
        plutobtm.setText("PLUTO");
        plutobtm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        plutobtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plutobtmActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(37, 36, 36));
        jSeparator3.setForeground(new java.awt.Color(37, 36, 36));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout taskbarbgLayout = new javax.swing.GroupLayout(taskbarbg);
        taskbarbg.setLayout(taskbarbgLayout);
        taskbarbgLayout.setHorizontalGroup(
            taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(plutobtm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vsngralbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Juegosbtm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 665, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutgtm, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        taskbarbgLayout.setVerticalGroup(
            taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarbgLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskbarbgLayout.createSequentialGroup()
                .addGroup(taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, taskbarbgLayout.createSequentialGroup()
                        .addGroup(taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(taskbarbgLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vsngralbtm)
                                    .addComponent(Juegosbtm)))
                            .addGroup(taskbarbgLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(plutobtm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(taskbarbgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskbarbgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutgtm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskbarbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(taskbarbg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(736, 736, 736))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1276, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutgtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutgtmActionPerformed
        setVisible(false);
        Login lout1 = new Login();
        lout1.setVisible(true);
    }//GEN-LAST:event_logoutgtmActionPerformed

    private void vsngralbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsngralbtmActionPerformed
        Vgral vg = new Vgral();
        Cambiarcontent(vg.getFondo());
    }//GEN-LAST:event_vsngralbtmActionPerformed

    private void plutobtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plutobtmActionPerformed
        Panelmenu menu2 = new Panelmenu();
        Cambiarcontent(menu2.getFondo());
        
    }//GEN-LAST:event_plutobtmActionPerformed

    private void JuegosbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuegosbtmActionPerformed
        Juegosjf jjf = new Juegosjf();
        Cambiarcontent(jjf.getFondo());
    }//GEN-LAST:event_JuegosbtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Juegosbtm;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logoutgtm;
    private javax.swing.JToggleButton plutobtm;
    private javax.swing.JPanel taskbarbg;
    private javax.swing.JButton vsngralbtm;
    // End of variables declaration//GEN-END:variables
}
