/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pluto;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        userlabel = new javax.swing.JLabel();
        Txtusuario = new javax.swing.JTextField();
        passlabel = new javax.swing.JLabel();
        registerlabel = new javax.swing.JLabel();
        registerbtm = new javax.swing.JButton();
        taskbarbg = new javax.swing.JPanel();
        plutotxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Txtpass = new javax.swing.JPasswordField();
        Txtreppass = new javax.swing.JPasswordField();
        reppasslabel = new javax.swing.JLabel();
        nombrelabel = new javax.swing.JLabel();
        apellidolabel = new javax.swing.JLabel();
        Textocredenciales = new javax.swing.JLabel();
        maillabel = new javax.swing.JLabel();
        Txtmail = new javax.swing.JTextField();
        Txtnombre = new javax.swing.JTextField();
        Txtapellido = new javax.swing.JTextField();
        volverbtm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(37, 36, 36));
        bg.setPreferredSize(new java.awt.Dimension(911, 550));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userlabel.setForeground(new java.awt.Color(212, 212, 212));
        userlabel.setText("Usuario");
        bg.add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));
        bg.add(Txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 250, -1));

        passlabel.setForeground(new java.awt.Color(212, 212, 212));
        passlabel.setText("Contraseña");
        bg.add(passlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 20));

        registerlabel.setBackground(new java.awt.Color(212, 212, 212));
        registerlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerlabel.setForeground(new java.awt.Color(212, 212, 212));
        registerlabel.setText("Registro");
        registerlabel.setToolTipText("");
        bg.add(registerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        registerbtm.setBackground(new java.awt.Color(247, 147, 50));
        registerbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerbtm.setForeground(new java.awt.Color(0, 0, 0));
        registerbtm.setText("Registrar");
        registerbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtmActionPerformed(evt);
            }
        });
        bg.add(registerbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 116, -1));

        taskbarbg.setBackground(new java.awt.Color(0, 0, 0));
        taskbarbg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        plutotxt.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        plutotxt.setForeground(new java.awt.Color(247, 147, 50));
        plutotxt.setText("PLUTO");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pluto/images/logochichitofinal.png"))); // NOI18N

        javax.swing.GroupLayout taskbarbgLayout = new javax.swing.GroupLayout(taskbarbg);
        taskbarbg.setLayout(taskbarbgLayout);
        taskbarbgLayout.setHorizontalGroup(
            taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarbgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plutotxt)
                .addContainerGap(724, Short.MAX_VALUE))
        );
        taskbarbgLayout.setVerticalGroup(
            taskbarbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarbgLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(taskbarbgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(plutotxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(taskbarbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 70));

        Txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtpassActionPerformed(evt);
            }
        });
        bg.add(Txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 250, -1));

        Txtreppass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtreppassActionPerformed(evt);
            }
        });
        bg.add(Txtreppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 250, -1));

        reppasslabel.setForeground(new java.awt.Color(212, 212, 212));
        reppasslabel.setText("Repetir contraseña");
        bg.add(reppasslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 20));

        nombrelabel.setForeground(new java.awt.Color(212, 212, 212));
        nombrelabel.setText("Nombre");
        bg.add(nombrelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, 20));

        apellidolabel.setForeground(new java.awt.Color(212, 212, 212));
        apellidolabel.setText("Apellido");
        bg.add(apellidolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, 20));

        Textocredenciales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Textocredenciales.setForeground(new java.awt.Color(247, 147, 50));
        Textocredenciales.setText("¡Asegurate de escribir bien tus credenciales!");
        bg.add(Textocredenciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        maillabel.setText("Mail");
        bg.add(maillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));
        bg.add(Txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 250, -1));

        Txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnombreActionPerformed(evt);
            }
        });
        bg.add(Txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 250, -1));
        bg.add(Txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 250, -1));

        volverbtm.setBackground(new java.awt.Color(37, 36, 36));
        volverbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volverbtm.setForeground(new java.awt.Color(204, 204, 204));
        volverbtm.setText("Volver");
        volverbtm.setBorder(null);
        volverbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbtmActionPerformed(evt);
            }
        });
        bg.add(volverbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 116, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtmActionPerformed
        Sqlusuario sqluser = new Sqlusuario();
        Usuario user1 = new Usuario();

        String pass = new String(Txtpass.getPassword());
        String repass = new String(Txtreppass.getPassword());

        if (Txtusuario.getText().equals("") || pass.equals("") || repass.equals("") || Txtnombre.getText().equals("")
                || Txtapellido.getText().equals("") || Txtmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llena los campos pa");
        } else {

            if (pass.equals(repass)) {

                if (sqluser.Reconocer_usuario(Txtusuario.getText()) == 0) {
                    user1.setUsuario(Txtusuario.getText());
                    user1.setContraseña(Txtpass.getText());
                    user1.setNombre(Txtnombre.getText());
                    user1.setApellido(Txtapellido.getText());
                    user1.setMail(Txtmail.getText());
                    if (sqluser.registrar_usuario(user1)) {
                        JOptionPane.showMessageDialog(null, "Cuenta creada!!");
                        Limpiar();
                        setVisible(false);
                        Login login1 = new Login();
                        login1.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Ocurrio un error :c");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario existente wachin");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no son iguales pa");
            }
        }

    }//GEN-LAST:event_registerbtmActionPerformed
    private void Limpiar() {
        Txtusuario.setText("");
        Txtpass.setText("");
        Txtreppass.setText("");
        Txtnombre.setText("");
        Txtapellido.setText("");
        Txtmail.setText("");
    }
    private void TxtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtpassActionPerformed

    private void TxtreppassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtreppassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtreppassActionPerformed

    private void TxtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnombreActionPerformed

    private void volverbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbtmActionPerformed
        setVisible(false);
        Login login2 = new Login();
        login2.setVisible(true);
    }//GEN-LAST:event_volverbtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Textocredenciales;
    public javax.swing.JTextField Txtapellido;
    public javax.swing.JTextField Txtmail;
    public javax.swing.JTextField Txtnombre;
    public javax.swing.JPasswordField Txtpass;
    public javax.swing.JPasswordField Txtreppass;
    public javax.swing.JTextField Txtusuario;
    private javax.swing.JLabel apellidolabel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maillabel;
    private javax.swing.JLabel nombrelabel;
    private javax.swing.JLabel passlabel;
    private javax.swing.JLabel plutotxt;
    private javax.swing.JButton registerbtm;
    private javax.swing.JLabel registerlabel;
    private javax.swing.JLabel reppasslabel;
    private javax.swing.JPanel taskbarbg;
    private javax.swing.JLabel userlabel;
    private javax.swing.JButton volverbtm;
    // End of variables declaration//GEN-END:variables
}
