/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pluto;

import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class seccionlearn extends javax.swing.JFrame {

    /**
     * Creates new form seccionlearn
     */
    public seccionlearn() {
        initComponents();
    }
    public JPanel getFondo() {
        return bg;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtagregarjuego = new javax.swing.JLabel();
        protegerinvpng = new javax.swing.JLabel();
        returnbtm = new javax.swing.JButton();
        thinkingbtm = new javax.swing.JButton();
        protegerbtm = new javax.swing.JButton();
        vsngralbtm = new javax.swing.JButton();
        thinkingpng = new javax.swing.JLabel();
        returnpng = new javax.swing.JLabel();
        estudiayaprende = new javax.swing.JLabel();
        estudiayaprende1 = new javax.swing.JLabel();
        estudiayaprende2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 0, 0));

        txtagregarjuego.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        txtagregarjuego.setForeground(new java.awt.Color(204, 204, 204));
        txtagregarjuego.setText("Aprende a invertir en el mundo de los Juegos NFTs");

        protegerinvpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pluto/images/proteger inversion.png"))); // NOI18N

        returnbtm.setBackground(new java.awt.Color(247, 147, 50));
        returnbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnbtm.setForeground(new java.awt.Color(0, 0, 0));
        returnbtm.setText("APRENDER");
        returnbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtmActionPerformed(evt);
            }
        });

        thinkingbtm.setBackground(new java.awt.Color(247, 147, 50));
        thinkingbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thinkingbtm.setForeground(new java.awt.Color(0, 0, 0));
        thinkingbtm.setText("APRENDER");
        thinkingbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thinkingbtmActionPerformed(evt);
            }
        });

        protegerbtm.setBackground(new java.awt.Color(247, 147, 50));
        protegerbtm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        protegerbtm.setForeground(new java.awt.Color(0, 0, 0));
        protegerbtm.setText("APRENDER");
        protegerbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protegerbtmActionPerformed(evt);
            }
        });

        vsngralbtm.setBackground(new java.awt.Color(37, 36, 36));
        vsngralbtm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vsngralbtm.setForeground(new java.awt.Color(204, 204, 204));
        vsngralbtm.setText("VER MAS");
        vsngralbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsngralbtmActionPerformed(evt);
            }
        });

        thinkingpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pluto/images/chabonsentadochiquito2.png"))); // NOI18N

        returnpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pluto/images/returnpng.png"))); // NOI18N

        estudiayaprende.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        estudiayaprende.setForeground(new java.awt.Color(204, 204, 204));
        estudiayaprende.setText("Protege tu inversión");

        estudiayaprende1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        estudiayaprende1.setForeground(new java.awt.Color(204, 204, 204));
        estudiayaprende1.setText("Identificá oportunidades");

        estudiayaprende2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        estudiayaprende2.setForeground(new java.awt.Color(204, 204, 204));
        estudiayaprende2.setText("Analiza tus resultados");

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Realiza un analisis de tus acciones");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Aprende a asegurar tu dinero");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Analiza los fundamentales de un juego ");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("para reconocer oportunidades");

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("para optimizar tus ganancias");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(estudiayaprende2))
                        .addGap(27, 27, 27))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(returnpng))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(returnbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel5)))
                        .addGap(42, 42, 42)))
                .addGap(187, 187, 187)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estudiayaprende)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(protegerbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(protegerinvpng, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(estudiayaprende1)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(thinkingpng)
                        .addGap(176, 176, 176))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(txtagregarjuego)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thinkingbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(vsngralbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(529, 529, 529))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(txtagregarjuego)
                .addGap(49, 49, 49)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thinkingpng)
                    .addComponent(returnpng)
                    .addComponent(protegerinvpng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estudiayaprende)
                    .addComponent(estudiayaprende2)
                    .addComponent(estudiayaprende1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thinkingbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(protegerbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(vsngralbtm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtmActionPerformed

    }//GEN-LAST:event_returnbtmActionPerformed

    private void thinkingbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thinkingbtmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thinkingbtmActionPerformed

    private void protegerbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protegerbtmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_protegerbtmActionPerformed

    private void vsngralbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsngralbtmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vsngralbtmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seccionlearn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seccionlearn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seccionlearn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seccionlearn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seccionlearn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel estudiayaprende;
    private javax.swing.JLabel estudiayaprende1;
    private javax.swing.JLabel estudiayaprende2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton protegerbtm;
    private javax.swing.JLabel protegerinvpng;
    private javax.swing.JButton returnbtm;
    private javax.swing.JLabel returnpng;
    private javax.swing.JButton thinkingbtm;
    private javax.swing.JLabel thinkingpng;
    private javax.swing.JLabel txtagregarjuego;
    private javax.swing.JButton vsngralbtm;
    // End of variables declaration//GEN-END:variables
}
